### ISSUE TITLE
how i can run it?

### ISSUE THREAD

**Issue by maxgu** [fesor/project-skeleton#4]
```shell
$ COMPOSER_GITHUB_TOKEN=XXX docker-compose up
Starting skeleton_database_1 ... 
Recreating skeleton_php_1 ... done
Recreating skeleton_front_1 ... done
Attaching to skeleton_database_1, skeleton_php_1, skeleton_front_1
...
```
i add template.docker to my /etc/hosts (127.0.0.1 template.docker)
and http://localhost, http://localhost:8080, http://template.docker, http://template.docker:8080 - not working

**Comment by fesor** [comment]
You need [dinghy http proxy](https://github.com/codekitchen/dinghy-http-proxy).

The idea is that only this proxy container will expose port on your host machine.

**Comment by maxgu** [comment]
or i can add 
```
        ports:
            - 80:80
            - 443:443
```
in front section in docker/docker-compose.yml
